#!/usr/bin/env bash
# Clone remote marketplace plugins into ./plugins for local browsing.
# Local plugins (string sources) stay tracked. Remote clones are gitignored.
set -euo pipefail

root=$(cd "$(dirname "$0")/.." && pwd)
marketplace="$root/.claude-plugin/marketplace.json"
plugins="$root/plugins"
ignore="$plugins/.gitignore"

[[ -f $marketplace ]] || { echo "missing $marketplace" >&2; exit 1; }
mkdir -p "$plugins"

jobs=$(python3 - "$marketplace" <<'PY'
import json, sys

data = json.load(open(sys.argv[1]))
for plugin in data.get("plugins", []):
    name = plugin.get("name")
    src = plugin.get("source")
    if not name or src is None:
        continue
    if isinstance(src, str):
        continue
    kind = src.get("source")
    ref = src.get("ref") or ""
    if kind == "github" and src.get("repo"):
        print("\t".join(["github", name, src["repo"], "", ref]))
    elif kind == "url" and src.get("url"):
        print("\t".join(["url", name, src["url"], "", ref]))
    elif kind == "git-subdir" and src.get("url") and src.get("path"):
        print("\t".join(["git-subdir", name, src["url"], src["path"], ref]))
    else:
        print("skip\t%s\t%s" % (name, kind or "?"), file=sys.stderr)
PY
)

{
  echo "# Remote marketplace clones. Regenerated by scripts/clone-remote-plugins.sh"
  echo "# Local plugins (string sources in marketplace.json) stay tracked."
  if [[ -n "${jobs}" ]]; then
    printf '%s\n' "$jobs" | awk -F '\t' '{print $2 "/"}'
  fi
} > "$ignore"

clone_git() {
  local dest=$1 url=$2 ref=$3
  if [[ -d $dest/.git ]]; then
    git -C "$dest" pull --ff-only --depth 1
    return
  fi
  rm -rf "$dest"
  if [[ -n $ref ]]; then
    git clone --depth 1 --filter=blob:none --branch "$ref" "$url" "$dest"
  else
    git clone --depth 1 --filter=blob:none "$url" "$dest"
  fi
}

clone_subdir() {
  local dest=$1 url=$2 path=$3 ref=$4
  local tmp
  tmp=$(mktemp -d)
  trap 'rm -rf "$tmp"' RETURN
  if [[ -n $ref ]]; then
    git clone --depth 1 --filter=blob:none --sparse --branch "$ref" "$url" "$tmp"
  else
    git clone --depth 1 --filter=blob:none --sparse "$url" "$tmp"
  fi
  git -C "$tmp" sparse-checkout set "$path"
  [[ -d $tmp/$path ]] || { echo "no path $path in $url" >&2; return 1; }
  rm -rf "$dest"
  mkdir -p "$dest"
  cp -a "$tmp/$path"/. "$dest/"
}

[[ -z "${jobs}" ]] && { echo "no remote plugins"; exit 0; }

while IFS=$'\t' read -r kind name a b ref; do
  dest="$plugins/$name"
  if [[ -e $dest ]] && ! git -C "$root" check-ignore -q "$dest"; then
    echo "skip $name (tracked local plugin)"
    continue
  fi
  echo "$kind $name"
  case $kind in
    github) clone_git "$dest" "https://github.com/${a}.git" "$ref" ;;
    url) clone_git "$dest" "$a" "$ref" ;;
    git-subdir) clone_subdir "$dest" "$a" "$b" "$ref" ;;
  esac
done <<< "$jobs"
